### ISSUE TITLE
Recommendation for including/excluding specific pkginfo names?

### ISSUE THREAD

**Issue by homebysix** [jc0b/munki-promoter#8]
I'd like to migrate from our custom Munki promotion script to this one. However one of the important features of our custom script is that it only includes a specific list of pkginfo `name`s that we are confident in promoting automatically. If a pkginfo `name` is not on this list, we must promote it manually (for now, until it earns our confidence).

Long-term our goal is to transition from this inclusion list to an exclusion list — a list of `name`s that we always want to promote manually. If a `name` is not on this list, it would then be promoted automatically after our default number of days.

Does your munki-promoter tool offer either an inclusions or exclusions capability, or do you have any interest in a pull request that would add such capability?

Thank you!

**Comment by jc0b** [comment]
Hello! Thanks for the interest, and thanks for the feedback!

We have added an inclusions/exclusions capability, which lets you define a list of items by pkginfo `name` that you want to include/exclude from promotion. At the moment, these changes are still [in the `dev` branch](https://github.com/jc0b/munki-promoter/compare/main...dev), but [the wiki has been updated to include documentation for the new keys](https://github.com/jc0b/munki-promoter/wiki/Supported-Configuration-Keys#selection).

An example of how this would be represented in the configuration file is below:
```yaml
---
  promotions:
    autopkg:
      promote_to:
        - "staging"
        - "autopkg"
    staging:
      promote_to:
        - "production"
      promote_from:
        - "autopkg"
        - "staging"
      custom_items:
        GoogleChrome: 
          days_in_catalog: 3
    staging_manual:
      promote_to:
        - "production"
      promote_from:
        - "staging"
      days_in_catalog: 30
  default_days_in_catalog : 5
  selection:
    type: "inclusion"
    items:
      - "SublimeText4"
```

Please let us know what you think of this - happy to accept feedback and tweak things before merging it and tagging a new release :) Thanks!
